// generate_static.ts — writes everything static the build produces:
//   src/routes.generated.ts   route registry (paths + hydration payloads)
//   dist/_redirects           alias 301s, dynamic-route 404s, SPA fallback
//   dist/robots.txt           indexable vs noindex per deploy context
//   dist/_headers             X-Robots-Tag noindex on previews
//   dist/sitemap.xml          indexable URLs only
//   dist/feeds/reviews.xml    latest-reviews RSS
//
//   vite-node scripts/generate_static.ts   (after export_prerender_data.ts)
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  loadData,
  indexableUniversities,
  universitiesPageData,
  citiesData,
  universityPageData,
  aliasRedirects,
  reviewsPageData,
  allCities,
  allHubs,
  hubPageData,
} from './lib/staticData'
import { TRUST_PAGES } from '../src/lib/trustContent'
import { buildEnv } from './lib/env'
import { SITE, PROD_ORIGIN, siteUrl } from '../src/lib/seo/site'
import { escapeAttr } from '../src/lib/seo/escape'

const FRONTEND = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DATA_DIR = resolve(FRONTEND, '.prerender-data')
const DIST = resolve(FRONTEND, 'dist')
const env = buildEnv(FRONTEND)

// Indexable output only on the real production deploy (or explicit override).
// Staging, deploy previews and local builds emit noindex robots/headers.
const isProdDeploy =
  env.TRC_INDEXABLE === '1' ||
  (env.CONTEXT === 'production' && (env.URL ?? '').includes('therealchina.net'))
console.log(
  `deploy context: ${env.CONTEXT ?? 'local'} → ${isProdDeploy ? 'INDEXABLE' : 'noindex'} output`
)

const { universities, stats, reviews, authors, upvotes } = loadData(DATA_DIR)
const indexableUnis = indexableUniversities(universities, reviews)
console.log(
  `${universities.length} universities · ${indexableUnis.length} indexable (≥1 substantive review)`
)

// ── Route registry ──────────────────────────────────────────────────────────
interface RouteEntry {
  path: string
  data: Record<string, unknown>
}
const indexData = () => ({
  universitiesPage: {
    for: { search: '', city: '', sortBy: 'reviews', page: 1 },
    ...universitiesPageData(universities, stats),
  },
  cities: citiesData(universities),
})

const cities = allCities(universities, reviews, stats)
const hubs = allHubs(universities, reviews, stats)

const routes: RouteEntry[] = [
  { path: '/', data: indexData() },
  { path: '/universities', data: indexData() },
  {
    path: '/reviews',
    data: { reviewsPage: reviewsPageData(reviews, universities, authors, upvotes) },
  },
  // City hubs — only indexable ones are prerendered; thin cities go through
  // the SPA shell with noindex (rule emitted below).
  ...cities
    .filter((c) => c.indexable)
    .map((c) => ({
      path: `/city/${c.slug}`,
      data: {
        cityPage: { city: c.city, universities: c.universities, reviewCount: c.reviewCount },
      },
    })),
  // Program/degree hubs — same: only substantive-review hubs prerender.
  ...hubs
    .filter((h) => h.indexable)
    .map((h) => ({
      path: `/${h.kind}/${h.hub.slug}`,
      data: { hubPage: hubPageData(h, authors, upvotes) },
    })),
  // Trust/legal pages — always indexable, static content.
  ...TRUST_PAGES.map((d) => ({ path: `/${d.slug}`, data: {} })),
  ...indexableUnis.map((u) => ({
    path: `/university/${u.slug}`,
    data: { universityPage: universityPageData(u, reviews, stats, authors) },
  })),
]

const routesTs = `// GENERATED by scripts/generate_static.ts — do not hand-edit.
// The prerendered-route registry: every indexable path + the hydration payload
// embedded into its HTML. Regenerate with npm run generate:static.
export const PRERENDER_ROUTES: { path: string; data: Record<string, unknown> }[] =
  ${JSON.stringify(routes, null, 2).replace(/"([a-zA-Z_$][a-zA-Z0-9_$]*)":/g, '$1:')} as const
`
writeFileSync(resolve(FRONTEND, 'src/routes.generated.ts'), routesTs)

// ── _redirects ──────────────────────────────────────────────────────────────
// Resolution order (first match wins; static files always beat non-forced
// rules): alias 301 → valid-but-thin slugs served the SPA shell (noindex)
// → anything else under a dynamic prefix is a real 404 → SPA fallback.
const prerenderedSlugs = new Set(indexableUnis.map((u) => u.slug))
const spaOnlySlugs = universities.filter((u) => !prerenderedSlugs.has(u.slug))
const prerenderedHubs = new Set(
  hubs.filter((h) => h.indexable).map((h) => `/${h.kind}/${h.hub.slug}`)
)
const prerenderedCities = new Set(cities.filter((c) => c.indexable).map((c) => c.slug))

const redirects = [
  '# GENERATED by scripts/generate_static.ts — do not hand-edit.',
  '# Canonical host enforcement — the Netlify subdomain must never serve content',
  '# (duplicate site in Google). Force-301 everything to the www canonical host.',
  'https://therealchina.netlify.app/* https://www.therealchina.net/:splat 301!',
  '',
  '# Alias → canonical (permanent). Aliases are recorded in universities.slug_aliases.',
  ...aliasRedirects(universities).map((r) => `${r.from} ${r.to} 301`),
  '',
  '# Valid-but-thin pages → SPA shell (client-rendered, noindex).',
  ...spaOnlySlugs.map((u) => `/university/${u.slug} /app.html 200`),
  ...cities
    .filter((c) => !prerenderedCities.has(c.slug))
    .map((c) => `/city/${c.slug} /app.html 200`),
  ...hubs
    .filter((h) => !prerenderedHubs.has(`/${h.kind}/${h.hub.slug}`))
    .map((h) => `/${h.kind}/${h.hub.slug} /app.html 200`),
  '',
  '# Unknown slugs under dynamic prefixes → real 404 (existing files still win).',
  '/university/* /404.html 404',
  '/city/* /404.html 404',
  '/program/* /404.html 404',
  '/degree/* /404.html 404',
  '/guide/* /404.html 404',
  '/authors/* /404.html 404',
  '',
  '# SPA fallback — app shell, not a content page.',
  '/* /app.html 200',
  '',
].join('\n')
writeFileSync(resolve(DIST, '_redirects'), redirects)

// ── robots.txt + _headers ───────────────────────────────────────────────────
const robots = isProdDeploy
  ? `User-agent: *\nAllow: /\n\nSitemap: ${PROD_ORIGIN}/sitemap.xml\n`
  : `User-agent: *\nDisallow: /\n`
writeFileSync(resolve(DIST, 'robots.txt'), robots)

const headers = isProdDeploy
  ? `# GENERATED — production deploy, no extra SEO headers required.\n`
  : `# GENERATED — non-production deploy: keep everything out of the index.\n/*\n  X-Robots-Tag: noindex, nofollow\n`
writeFileSync(resolve(DIST, '_headers'), headers)

// ── sitemap.xml ─────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10)
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (r) => `  <url>
    <loc>${escapeAttr(siteUrl(r.path))}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.path === '/' ? 'daily' : 'weekly'}</changefreq>
    <priority>${r.path === '/' ? '1.0' : '0.8'}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`
writeFileSync(resolve(DIST, 'sitemap.xml'), sitemap)

// ── RSS: latest reviews ─────────────────────────────────────────────────────
const uniById = new Map(universities.map((u) => [u.id, u]))
const latest = [...reviews].sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, 25)
const items = latest
  .map((r) => {
    const uni = uniById.get(r.university_id)
    if (!uni) return ''
    const link = `${PROD_ORIGIN}/university/${uni.slug}#review-${r.id}`
    const title = escapeAttr(`${uni.name} — ${'★'.repeat(r.rating)}`)
    const desc = escapeAttr((r.text ?? '').slice(0, 500))
    return `  <item>
    <title>${title}</title>
    <link>${escapeAttr(link)}</link>
    <guid isPermaLink="true">${escapeAttr(link)}</guid>
    <pubDate>${new Date(r.created_at).toUTCString()}</pubDate>
    <description>${desc}</description>
  </item>`
  })
  .filter(Boolean)
  .join('\n')
const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
  <title>${escapeAttr(SITE.name)} — Latest university reviews</title>
  <link>${PROD_ORIGIN}</link>
  <description>${escapeAttr(SITE.defaultDescription)}</description>
  <language>en</language>
${items}
</channel>
</rss>
`
mkdirSync(resolve(DIST, 'feeds'), { recursive: true })
writeFileSync(resolve(DIST, 'feeds/reviews.xml'), rss)

console.log(
  `routes.generated.ts: ${routes.length} routes · _redirects: ${aliasRedirects(universities).length} aliases · sitemap: ${routes.length} urls · rss: ${latest.length} items`
)
