// GENERATED by scripts/generate_static.ts — do not hand-edit.
// The prerendered-route registry: every indexable path + the hydration payload
// embedded into its HTML. Regenerate with npm run generate:static.
export const PRERENDER_ROUTES: { path: string; data: Record<string, unknown> }[] =
  [
  {
    path: "/",
    data: {
      universitiesPage: {
        for: {
          search: "",
          city: "",
          sortBy: "reviews",
          page: 1
        },
        rows: [
          {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4.4,
            review_count: 5,
            recommendYesPct: 67,
            recommendAnswered: 3
          },
          {
            id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 3,
            review_count: 3,
            recommendYesPct: 0,
            recommendAnswered: 2
          },
          {
            id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4.5,
            review_count: 2,
            recommendYesPct: 0,
            recommendAnswered: 1
          },
          {
            id: "c65bcba3-62cf-401a-a430-067361d3060a",
            name: "Nanjing University",
            name_zh: "南京大学",
            city: "Nanjing",
            country: "China",
            province: "Jiangsu",
            uni_category: "comprehensive",
            slug: "nanjing-university",
            slug_aliases: [
              "nju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/44696062.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.nju.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/nanjing-university",
              shanghai_national: 6
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "ae41de90-55b9-45d0-b7e9-f58e6867ed6a",
            name: "Sichuan University",
            name_zh: "四川大学",
            city: "Chengdu",
            country: "China",
            province: "Sichuan",
            uni_category: "comprehensive",
            slug: "sichuan-university",
            slug_aliases: [
              "scu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/75651370.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://en.scu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/sichuan-university",
              shanghai_national: 15
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 3,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "391322ba-4d02-4740-93a3-17cbb0814e50",
            name: "Wuhan University",
            name_zh: "武汉大学",
            city: "Wuhan",
            country: "China",
            province: "Hubei",
            uni_category: "comprehensive",
            slug: "wuhan-university",
            slug_aliases: [
              "whu",
              "wuhan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/46182017.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.whu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/wuhan-university",
              shanghai_national: 8
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "4c9e0559-dca0-494e-8939-9140333f2853",
            name: "Xiamen University",
            name_zh: "厦门大学",
            city: "Xiamen",
            country: "China",
            province: "Fujian",
            uni_category: "comprehensive",
            slug: "xiamen-university",
            slug_aliases: [
              "xmu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/14008229.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.xmu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/xiamen-university",
              shanghai_national: 24
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "15481968-7487-49fe-a72c-ed979c9a5add",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "c91a856d-8aee-418e-ad29-b2db84b3b072",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "d7713e08-9547-4ddd-80b5-3bed9b3b5872",
            name: "Hunan University",
            name_zh: "湖南大学",
            city: "Changsha",
            country: "China",
            province: "Hunan",
            uni_category: "comprehensive",
            slug: "hunan-university",
            slug_aliases: [
              "hnu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/79015808.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://www.hnu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/hunan-university",
              shanghai_national: 29
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "e2fb01ae-c2ec-44bd-907e-7461d0855603",
            name: "Tianjin University",
            name_zh: "天津大学",
            city: "Tianjin",
            country: "China",
            province: "Tianjin",
            uni_category: "comprehensive",
            slug: "tianjin-university",
            slug_aliases: [
              "tju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/74813674.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tianjin-university",
              shanghai_national: 20
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          }
        ],
        totalCount: 12,
        pageCount: 1
      },
      cities: {
        cities: [
          "Beijing",
          "Changsha",
          "Chengdu",
          "Hangzhou",
          "Nanjing",
          "Shanghai",
          "Tianjin",
          "Wuhan",
          "Xiamen"
        ],
        groups: [
          {
            province: null,
            cities: [
              "Beijing",
              "Shanghai",
              "Tianjin"
            ]
          },
          {
            province: "Fujian",
            cities: [
              "Xiamen"
            ]
          },
          {
            province: "Hubei",
            cities: [
              "Wuhan"
            ]
          },
          {
            province: "Hunan",
            cities: [
              "Changsha"
            ]
          },
          {
            province: "Jiangsu",
            cities: [
              "Nanjing"
            ]
          },
          {
            province: "Sichuan",
            cities: [
              "Chengdu"
            ]
          },
          {
            province: "Zhejiang",
            cities: [
              "Hangzhou"
            ]
          }
        ]
      }
    }
  },
  {
    path: "/universities",
    data: {
      universitiesPage: {
        for: {
          search: "",
          city: "",
          sortBy: "reviews",
          page: 1
        },
        rows: [
          {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4.4,
            review_count: 5,
            recommendYesPct: 67,
            recommendAnswered: 3
          },
          {
            id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 3,
            review_count: 3,
            recommendYesPct: 0,
            recommendAnswered: 2
          },
          {
            id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4.5,
            review_count: 2,
            recommendYesPct: 0,
            recommendAnswered: 1
          },
          {
            id: "c65bcba3-62cf-401a-a430-067361d3060a",
            name: "Nanjing University",
            name_zh: "南京大学",
            city: "Nanjing",
            country: "China",
            province: "Jiangsu",
            uni_category: "comprehensive",
            slug: "nanjing-university",
            slug_aliases: [
              "nju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/44696062.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.nju.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/nanjing-university",
              shanghai_national: 6
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "ae41de90-55b9-45d0-b7e9-f58e6867ed6a",
            name: "Sichuan University",
            name_zh: "四川大学",
            city: "Chengdu",
            country: "China",
            province: "Sichuan",
            uni_category: "comprehensive",
            slug: "sichuan-university",
            slug_aliases: [
              "scu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/75651370.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://en.scu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/sichuan-university",
              shanghai_national: 15
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 3,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "391322ba-4d02-4740-93a3-17cbb0814e50",
            name: "Wuhan University",
            name_zh: "武汉大学",
            city: "Wuhan",
            country: "China",
            province: "Hubei",
            uni_category: "comprehensive",
            slug: "wuhan-university",
            slug_aliases: [
              "whu",
              "wuhan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/46182017.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.whu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/wuhan-university",
              shanghai_national: 8
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "4c9e0559-dca0-494e-8939-9140333f2853",
            name: "Xiamen University",
            name_zh: "厦门大学",
            city: "Xiamen",
            country: "China",
            province: "Fujian",
            uni_category: "comprehensive",
            slug: "xiamen-university",
            slug_aliases: [
              "xmu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/14008229.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.xmu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/xiamen-university",
              shanghai_national: 24
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "15481968-7487-49fe-a72c-ed979c9a5add",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "c91a856d-8aee-418e-ad29-b2db84b3b072",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "d7713e08-9547-4ddd-80b5-3bed9b3b5872",
            name: "Hunan University",
            name_zh: "湖南大学",
            city: "Changsha",
            country: "China",
            province: "Hunan",
            uni_category: "comprehensive",
            slug: "hunan-university",
            slug_aliases: [
              "hnu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/79015808.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://www.hnu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/hunan-university",
              shanghai_national: 29
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "e2fb01ae-c2ec-44bd-907e-7461d0855603",
            name: "Tianjin University",
            name_zh: "天津大学",
            city: "Tianjin",
            country: "China",
            province: "Tianjin",
            uni_category: "comprehensive",
            slug: "tianjin-university",
            slug_aliases: [
              "tju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/74813674.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tianjin-university",
              shanghai_national: 20
            },
            created_at: "2026-09-24T11:56:09.009128+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          }
        ],
        totalCount: 12,
        pageCount: 1
      },
      cities: {
        cities: [
          "Beijing",
          "Changsha",
          "Chengdu",
          "Hangzhou",
          "Nanjing",
          "Shanghai",
          "Tianjin",
          "Wuhan",
          "Xiamen"
        ],
        groups: [
          {
            province: null,
            cities: [
              "Beijing",
              "Shanghai",
              "Tianjin"
            ]
          },
          {
            province: "Fujian",
            cities: [
              "Xiamen"
            ]
          },
          {
            province: "Hubei",
            cities: [
              "Wuhan"
            ]
          },
          {
            province: "Hunan",
            cities: [
              "Changsha"
            ]
          },
          {
            province: "Jiangsu",
            cities: [
              "Nanjing"
            ]
          },
          {
            province: "Sichuan",
            cities: [
              "Chengdu"
            ]
          },
          {
            province: "Zhejiang",
            cities: [
              "Hangzhou"
            ]
          }
        ]
      }
    }
  },
  {
    path: "/reviews",
    data: {
      reviewsPage: {
        reviews: [
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "One-semester exchange. The language classes were excellent and the campus is genuinely beautiful, but the international office was slow with paperwork — start your visa admin early.",
            program: "Chinese Language",
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-tsinghua-canteen.jpg",
                name: "canteen.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-20T11:56:09.009128+00:00",
            enrollment_status: "exchange",
            start_year: 2024,
            end_year: 2025,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: null,
            living_cost_range: "¥4k–¥8k",
            funding_type: "school",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: "Amazing campus life, great food, easy to meet people through clubs.",
            cons: "International office response times; dorm heating is centrally controlled.",
            tags: [
              "Great food",
              "International-friendly",
              "Beautiful campus",
              "Good nightlife"
            ],
            rating_academics: 4,
            rating_campus: 5,
            rating_accommodation: null,
            rating_cost: 4,
            rating_intl_office: 3,
            rating_social: 5,
            rating_extracurricular: 4,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14",
            university_id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            user_id: null,
            rating: 4,
            text: "Great name and brilliant classmates, but the admin is a maze — every form needs three stamps and two offices. Worth it if you are patient and your Chinese is solid.",
            program: "Economics",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-18T11:56:09.009128+00:00",
            enrollment_status: "current",
            start_year: 2022,
            end_year: null,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "province",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Great food",
              "Hard bureaucracy"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 3,
            rating_intl_office: 3,
            rating_social: 4,
            rating_extracurricular: null,
            rating_career: 4
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "Studied here 2018–2022. Brutal grading but employers across Asia know the name — it opened doors everywhere. Dorms are basic; bring your own kettle and lower your expectations.",
            program: "Mechanical Engineering",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-15T11:56:09.009128+00:00",
            enrollment_status: "alumni",
            start_year: 2018,
            end_year: 2022,
            language_of_instruction: "Bilingual",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥2k–¥4k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "yes",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Hard grading",
              "Good career support"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 3,
            rating_cost: 4,
            rating_intl_office: null,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16",
            university_id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            user_id: null,
            rating: 3,
            text: "Fun semester and the food scene is unbeatable, but everything near campus is expensive and my dorm had mold. Come for the city, not the facilities.",
            program: null,
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-fudan-street.jpg",
                name: "street-food.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-fudan-river.jpg",
                name: "suzhou-creek.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-13T11:56:09.009128+00:00",
            enrollment_status: "exchange",
            start_year: 2022,
            end_year: 2023,
            language_of_instruction: "English",
            tuition_range: null,
            living_cost_range: "Over ¥8k",
            funding_type: null,
            funding_coverage: null,
            recommend: "no",
            pros: "Unbeatable food and nightlife; easy city to live in as a foreigner.",
            cons: "Dorm quality and prices near campus.",
            tags: [
              "Expensive city",
              "Good nightlife",
              "Great food"
            ],
            rating_academics: null,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: null,
            rating_social: 4,
            rating_extracurricular: 3,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T11:56:09.009128+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
            university_id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            user_id: null,
            rating: 2,
            text: "Shanghai is an amazing city but the program felt overpriced for what you get. International office support was thin when I needed visa help, and nobody warned me about the living costs.",
            program: "Journalism",
            degree_level: "Master",
            media: [],
            created_at: "2026-09-03T11:56:09.009128+00:00",
            enrollment_status: "alumni",
            start_year: 2019,
            end_year: 2021,
            language_of_instruction: "English",
            tuition_range: "¥80k–¥150k",
            living_cost_range: "Over ¥8k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "no",
            pros: null,
            cons: "Tuition plus Shanghai rent adds up fast; support for international students was limited.",
            tags: [
              "Expensive city",
              "Hard bureaucracy"
            ],
            rating_academics: 3,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: 2,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 2
          },
          {
            id: "ad7c7b2e-7128-4f66-8bdf-45d92553a7b6",
            university_id: "4c9e0559-dca0-494e-8939-9140333f2853",
            user_id: null,
            rating: 5,
            text: "Xiamen University is right on the beach — literally. The architecture is gorgeous, the seafood is cheap, and the people are warm. One of the most underrated campuses in China.",
            program: "Marine Biology",
            degree_level: "Bachelor",
            media: [],
            created_at: "2025-04-10T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "10f9bee7-598e-406d-90c5-92f5ddce7543",
            university_id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            user_id: null,
            rating: 5,
            text: "PKU has the most beautiful campus I have ever seen — Weiming Lake in autumn is unreal. The Chinese language program for international students is excellent and very affordable.",
            program: "Chinese Language",
            degree_level: "Certificate",
            media: [],
            created_at: "2025-04-02T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "343eb70d-a212-402e-9231-35d088e600f0",
            university_id: "391322ba-4d02-4740-93a3-17cbb0814e50",
            user_id: null,
            rating: 5,
            text: "Wuhan University during cherry blossom season is one of the most beautiful places on earth. The sociology department is very welcoming to international researchers.",
            program: "Sociology",
            degree_level: "PhD",
            media: [],
            created_at: "2025-03-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "f22d0065-0858-4a1c-8f9a-9b347d4a4419",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "25a471d8-0758-4cc3-a7e7-dba12b097b8b",
            university_id: "c65bcba3-62cf-401a-a430-067361d3060a",
            user_id: null,
            rating: 4,
            text: "Nanjing University has a strong liberal arts tradition. The history department is fantastic and the city of Nanjing is rich in culture. Cost of living is much lower than Beijing or Shanghai.",
            program: "History",
            degree_level: "PhD",
            media: [],
            created_at: "2025-03-05T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "dbbd6d33-461b-4023-a8bf-e0db86bdbfae",
            university_id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            user_id: null,
            rating: 4,
            text: "SJTU has a massive, modern campus in Minhang. The engineering labs are top-notch. Commute to downtown Shanghai is long but the campus itself has everything you need.",
            program: "Mechanical Engineering",
            degree_level: "Master",
            media: [],
            created_at: "2025-02-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "b13e4b25-7d4b-4276-af6c-a294f358b224",
            university_id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            user_id: null,
            rating: 4,
            text: "Shanghai life is unbeatable. Fudan has strong international programs and the career fairs are well-connected. Cafeteria food could be better but there are cheap eats everywhere nearby.",
            program: "International Relations",
            degree_level: "Bachelor",
            media: [],
            created_at: "2025-02-11T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "b3759da6-efb1-4265-8d85-4d546c881a01",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "Great academics, but the workload is no joke. Be prepared to study hard. The international office was helpful with my visa extension though.",
            program: "Environmental Engineering",
            degree_level: "PhD",
            media: [],
            created_at: "2025-01-22T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "2b6daf95-c8ac-45da-8a5c-9c94df6e71be",
            university_id: "15481968-7487-49fe-a72c-ed979c9a5add",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "a1533b9d-dfba-4180-a120-3b454a065497",
            university_id: "ae41de90-55b9-45d0-b7e9-f58e6867ed6a",
            user_id: null,
            rating: 3,
            text: "Sichuan University has good medical programs but the international student support was hit or miss. Chengdu itself is amazing though — the food scene is incredible and rent is very affordable.",
            program: "Clinical Medicine",
            degree_level: "Bachelor",
            media: [],
            created_at: "2024-12-20T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          }
        ],
        universities: {
          "7c7a76b6-5de7-4921-943f-9679503658fa": {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            slug: "tsinghua-university"
          },
          "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545": {
            id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            name: "Peking University",
            slug: "peking-university"
          },
          "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f": {
            id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            name: "Fudan University",
            slug: "fudan-university"
          },
          "51d448cd-9483-4388-9619-c4d488afbaf8": {
            id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            name: "Shanghai Jiao Tong University",
            slug: "shanghai-jiao-tong-university"
          },
          "15481968-7487-49fe-a72c-ed979c9a5add": {
            id: "15481968-7487-49fe-a72c-ed979c9a5add",
            name: "Zhejiang University",
            slug: "zhejiang-university"
          },
          "391322ba-4d02-4740-93a3-17cbb0814e50": {
            id: "391322ba-4d02-4740-93a3-17cbb0814e50",
            name: "Wuhan University",
            slug: "wuhan-university"
          },
          "ae41de90-55b9-45d0-b7e9-f58e6867ed6a": {
            id: "ae41de90-55b9-45d0-b7e9-f58e6867ed6a",
            name: "Sichuan University",
            slug: "sichuan-university"
          },
          "4c9e0559-dca0-494e-8939-9140333f2853": {
            id: "4c9e0559-dca0-494e-8939-9140333f2853",
            name: "Xiamen University",
            slug: "xiamen-university"
          },
          "c65bcba3-62cf-401a-a430-067361d3060a": {
            id: "c65bcba3-62cf-401a-a430-067361d3060a",
            name: "Nanjing University",
            slug: "nanjing-university"
          }
        },
        authors: {}
      }
    }
  },
  {
    path: "/city/beijing",
    data: {
      cityPage: {
        city: "Beijing",
        universities: [
          {
            id: "c91a856d-8aee-418e-ad29-b2db84b3b072",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "40dda9ae-0196-4a8a-aa3c-4a4b0eaca545",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          }
        ],
        reviewCount: 7
      }
    }
  },
  {
    path: "/city/shanghai",
    data: {
      cityPage: {
        city: "Shanghai",
        universities: [
          {
            id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          }
        ],
        reviewCount: 4
      }
    }
  },
  {
    path: "/program/computer-science",
    data: {
      hubPage: {
        kind: "program",
        hub: {
          slug: "computer-science",
          label: "Computer Science & IT",
          blurb: "CS, software engineering, AI and data programs reviewed by international students.",
          aliases: [
            "computer science",
            "cs",
            "computer science & technology",
            "software engineering",
            "information technology",
            "artificial intelligence",
            "ai",
            "data science",
            "big data",
            "machine learning",
            "cyber security",
            "information security"
          ]
        },
        universities: [
          {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "15481968-7487-49fe-a72c-ed979c9a5add",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          }
        ],
        reviews: [
          {
            id: "f22d0065-0858-4a1c-8f9a-9b347d4a4419",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "2b6daf95-c8ac-45da-8a5c-9c94df6e71be",
            university_id: "15481968-7487-49fe-a72c-ed979c9a5add",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T11:56:09.009128+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          }
        ],
        authors: {}
      }
    }
  },
  {
    path: "/degree/master",
    data: {
      hubPage: {
        kind: "degree",
        hub: {
          slug: "master",
          label: "Master's Programs",
          blurb: "Postgraduate taught and research masters reviewed by students.",
          aliases: [
            "master",
            "masters",
            "master's",
            "postgraduate",
            "ma",
            "msc",
            "meng"
          ]
        },
        universities: [
          {
            id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          },
          {
            id: "15481968-7487-49fe-a72c-ed979c9a5add",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T11:56:09.009128+00:00"
          }
        ],
        reviews: [
          {
            id: "f22d0065-0858-4a1c-8f9a-9b347d4a4419",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "2b6daf95-c8ac-45da-8a5c-9c94df6e71be",
            university_id: "15481968-7487-49fe-a72c-ed979c9a5add",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "dbbd6d33-461b-4023-a8bf-e0db86bdbfae",
            university_id: "51d448cd-9483-4388-9619-c4d488afbaf8",
            user_id: null,
            rating: 4,
            text: "SJTU has a massive, modern campus in Minhang. The engineering labs are top-notch. Commute to downtown Shanghai is long but the campus itself has everything you need.",
            program: "Mechanical Engineering",
            degree_level: "Master",
            media: [],
            created_at: "2025-02-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T11:56:09.009128+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
            university_id: "2fe12d5d-efc3-41ad-86fb-a1e6ed94177f",
            user_id: null,
            rating: 2,
            text: "Shanghai is an amazing city but the program felt overpriced for what you get. International office support was thin when I needed visa help, and nobody warned me about the living costs.",
            program: "Journalism",
            degree_level: "Master",
            media: [],
            created_at: "2026-09-03T11:56:09.009128+00:00",
            enrollment_status: "alumni",
            start_year: 2019,
            end_year: 2021,
            language_of_instruction: "English",
            tuition_range: "¥80k–¥150k",
            living_cost_range: "Over ¥8k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "no",
            pros: null,
            cons: "Tuition plus Shanghai rent adds up fast; support for international students was limited.",
            tags: [
              "Expensive city",
              "Hard bureaucracy"
            ],
            rating_academics: 3,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: 2,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 2
          }
        ],
        authors: {}
      }
    }
  },
  {
    path: "/about",
    data: {}
  },
  {
    path: "/contact",
    data: {}
  },
  {
    path: "/editorial-policy",
    data: {}
  },
  {
    path: "/how-we-verify",
    data: {}
  },
  {
    path: "/review-guidelines",
    data: {}
  },
  {
    path: "/data-sources",
    data: {}
  },
  {
    path: "/privacy",
    data: {}
  },
  {
    path: "/terms",
    data: {}
  },
  {
    path: "/disclaimer",
    data: {}
  },
  {
    path: "/report",
    data: {}
  },
  {
    path: "/university/tsinghua-university",
    data: {
      universityPage: {
        university: {
          id: "7c7a76b6-5de7-4921-943f-9679503658fa",
          name: "Tsinghua University",
          name_zh: "清华大学",
          city: "Beijing",
          country: "China",
          province: "Beijing",
          uni_category: "comprehensive",
          slug: "tsinghua-university",
          slug_aliases: [
            "tsinghua"
          ],
          logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
          is_verified: false,
          uni_type: "public",
          languages_of_instruction: [
            "Chinese",
            "English"
          ],
          website: "https://www.tsinghua.edu.cn/en/",
          rankings: {
            shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
            shanghai_national: 1
          },
          created_at: "2026-09-24T11:56:09.009128+00:00"
        },
        reviews: [
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "One-semester exchange. The language classes were excellent and the campus is genuinely beautiful, but the international office was slow with paperwork — start your visa admin early.",
            program: "Chinese Language",
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-tsinghua-canteen.jpg",
                name: "canteen.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-20T11:56:09.009128+00:00",
            enrollment_status: "exchange",
            start_year: 2024,
            end_year: 2025,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: null,
            living_cost_range: "¥4k–¥8k",
            funding_type: "school",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: "Amazing campus life, great food, easy to meet people through clubs.",
            cons: "International office response times; dorm heating is centrally controlled.",
            tags: [
              "Great food",
              "International-friendly",
              "Beautiful campus",
              "Good nightlife"
            ],
            rating_academics: 4,
            rating_campus: 5,
            rating_accommodation: null,
            rating_cost: 4,
            rating_intl_office: 3,
            rating_social: 5,
            rating_extracurricular: 4,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "Studied here 2018–2022. Brutal grading but employers across Asia know the name — it opened doors everywhere. Dorms are basic; bring your own kettle and lower your expectations.",
            program: "Mechanical Engineering",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-15T11:56:09.009128+00:00",
            enrollment_status: "alumni",
            start_year: 2018,
            end_year: 2022,
            language_of_instruction: "Bilingual",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥2k–¥4k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "yes",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Hard grading",
              "Good career support"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 3,
            rating_cost: 4,
            rating_intl_office: null,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T11:56:09.009128+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "f22d0065-0858-4a1c-8f9a-9b347d4a4419",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "b3759da6-efb1-4265-8d85-4d546c881a01",
            university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
            user_id: null,
            rating: 4,
            text: "Great academics, but the workload is no joke. Be prepared to study hard. The international office was helpful with my visa extension though.",
            program: "Environmental Engineering",
            degree_level: "PhD",
            media: [],
            created_at: "2025-01-22T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          }
        ],
        authors: {},
        stats: {
          university_id: "7c7a76b6-5de7-4921-943f-9679503658fa",
          avg_rating: 4.4,
          review_count: 5,
          has_verified_review: false,
          recommend_yes_count: 2,
          recommend_maybe_count: 1,
          recommend_no_count: 0,
          updated_at: "2026-09-24T11:56:09.009128+00:00"
        }
      }
    }
  }
] as const
