// GENERATED by scripts/generate_static.ts — do not hand-edit.
// The prerendered-route registry: every indexable path + the hydration payload
// embedded into its HTML. Regenerate with npm run generate:static.
export const PRERENDER_ROUTES: { path: string; data: Record<string, unknown> }[] =
  [
  {
    path: "/",
    data: {
      universitiesPage: {
        for: {
          search: "",
          city: "",
          sortBy: "reviews",
          page: 1
        },
        rows: [
          {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4.4,
            review_count: 5,
            recommendYesPct: 67,
            recommendAnswered: 3
          },
          {
            id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 3,
            review_count: 3,
            recommendYesPct: 0,
            recommendAnswered: 2
          },
          {
            id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4.5,
            review_count: 2,
            recommendYesPct: 0,
            recommendAnswered: 1
          },
          {
            id: "47a6670e-bc06-48ea-99b9-71d76b804215",
            name: "Nanjing University",
            name_zh: "南京大学",
            city: "Nanjing",
            country: "China",
            province: "Jiangsu",
            uni_category: "comprehensive",
            slug: "nanjing-university",
            slug_aliases: [
              "nju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/44696062.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.nju.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/nanjing-university",
              shanghai_national: 6
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "a548ce74-f26c-4649-95fb-2ab3ad53f96b",
            name: "Sichuan University",
            name_zh: "四川大学",
            city: "Chengdu",
            country: "China",
            province: "Sichuan",
            uni_category: "comprehensive",
            slug: "sichuan-university",
            slug_aliases: [
              "scu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/75651370.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://en.scu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/sichuan-university",
              shanghai_national: 15
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 3,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "372e17ef-cb93-40e7-a94a-a9d977983153",
            name: "Wuhan University",
            name_zh: "武汉大学",
            city: "Wuhan",
            country: "China",
            province: "Hubei",
            uni_category: "comprehensive",
            slug: "wuhan-university",
            slug_aliases: [
              "whu",
              "wuhan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/46182017.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.whu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/wuhan-university",
              shanghai_national: 8
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "387a8428-7cad-40e2-a26e-8fa95d27cca4",
            name: "Xiamen University",
            name_zh: "厦门大学",
            city: "Xiamen",
            country: "China",
            province: "Fujian",
            uni_category: "comprehensive",
            slug: "xiamen-university",
            slug_aliases: [
              "xmu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/14008229.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.xmu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/xiamen-university",
              shanghai_national: 24
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "8756f4c8-0702-4611-be81-a43ee2b994c1",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "db449532-8966-4ae9-9fea-3f8209281c92",
            name: "Hunan University",
            name_zh: "湖南大学",
            city: "Changsha",
            country: "China",
            province: "Hunan",
            uni_category: "comprehensive",
            slug: "hunan-university",
            slug_aliases: [
              "hnu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/79015808.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://www.hnu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/hunan-university",
              shanghai_national: 29
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "f1f54540-ec07-4304-9d78-ebf7d46b0baa",
            name: "Tianjin University",
            name_zh: "天津大学",
            city: "Tianjin",
            country: "China",
            province: "Tianjin",
            uni_category: "comprehensive",
            slug: "tianjin-university",
            slug_aliases: [
              "tju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/74813674.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tianjin-university",
              shanghai_national: 20
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          }
        ],
        totalCount: 12,
        pageCount: 1
      },
      cities: {
        cities: [
          "Beijing",
          "Changsha",
          "Chengdu",
          "Hangzhou",
          "Nanjing",
          "Shanghai",
          "Tianjin",
          "Wuhan",
          "Xiamen"
        ],
        groups: [
          {
            province: null,
            cities: [
              "Beijing",
              "Shanghai",
              "Tianjin"
            ]
          },
          {
            province: "Fujian",
            cities: [
              "Xiamen"
            ]
          },
          {
            province: "Hubei",
            cities: [
              "Wuhan"
            ]
          },
          {
            province: "Hunan",
            cities: [
              "Changsha"
            ]
          },
          {
            province: "Jiangsu",
            cities: [
              "Nanjing"
            ]
          },
          {
            province: "Sichuan",
            cities: [
              "Chengdu"
            ]
          },
          {
            province: "Zhejiang",
            cities: [
              "Hangzhou"
            ]
          }
        ]
      }
    }
  },
  {
    path: "/universities",
    data: {
      universitiesPage: {
        for: {
          search: "",
          city: "",
          sortBy: "reviews",
          page: 1
        },
        rows: [
          {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4.4,
            review_count: 5,
            recommendYesPct: 67,
            recommendAnswered: 3
          },
          {
            id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 3,
            review_count: 3,
            recommendYesPct: 0,
            recommendAnswered: 2
          },
          {
            id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4.5,
            review_count: 2,
            recommendYesPct: 0,
            recommendAnswered: 1
          },
          {
            id: "47a6670e-bc06-48ea-99b9-71d76b804215",
            name: "Nanjing University",
            name_zh: "南京大学",
            city: "Nanjing",
            country: "China",
            province: "Jiangsu",
            uni_category: "comprehensive",
            slug: "nanjing-university",
            slug_aliases: [
              "nju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/44696062.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.nju.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/nanjing-university",
              shanghai_national: 6
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "a548ce74-f26c-4649-95fb-2ab3ad53f96b",
            name: "Sichuan University",
            name_zh: "四川大学",
            city: "Chengdu",
            country: "China",
            province: "Sichuan",
            uni_category: "comprehensive",
            slug: "sichuan-university",
            slug_aliases: [
              "scu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/75651370.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://en.scu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/sichuan-university",
              shanghai_national: 15
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 3,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "372e17ef-cb93-40e7-a94a-a9d977983153",
            name: "Wuhan University",
            name_zh: "武汉大学",
            city: "Wuhan",
            country: "China",
            province: "Hubei",
            uni_category: "comprehensive",
            slug: "wuhan-university",
            slug_aliases: [
              "whu",
              "wuhan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/46182017.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.whu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/wuhan-university",
              shanghai_national: 8
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "387a8428-7cad-40e2-a26e-8fa95d27cca4",
            name: "Xiamen University",
            name_zh: "厦门大学",
            city: "Xiamen",
            country: "China",
            province: "Fujian",
            uni_category: "comprehensive",
            slug: "xiamen-university",
            slug_aliases: [
              "xmu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/14008229.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.xmu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/xiamen-university",
              shanghai_national: 24
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 5,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 4,
            review_count: 1,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "8756f4c8-0702-4611-be81-a43ee2b994c1",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "db449532-8966-4ae9-9fea-3f8209281c92",
            name: "Hunan University",
            name_zh: "湖南大学",
            city: "Changsha",
            country: "China",
            province: "Hunan",
            uni_category: "comprehensive",
            slug: "hunan-university",
            slug_aliases: [
              "hnu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/79015808.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese"
            ],
            website: "https://www.hnu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/hunan-university",
              shanghai_national: 29
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          },
          {
            id: "f1f54540-ec07-4304-9d78-ebf7d46b0baa",
            name: "Tianjin University",
            name_zh: "天津大学",
            city: "Tianjin",
            country: "China",
            province: "Tianjin",
            uni_category: "comprehensive",
            slug: "tianjin-university",
            slug_aliases: [
              "tju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/74813674.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tianjin-university",
              shanghai_national: 20
            },
            created_at: "2026-09-24T12:49:46.459163+00:00",
            avg_rating: 0,
            review_count: 0,
            recommendYesPct: null,
            recommendAnswered: 0
          }
        ],
        totalCount: 12,
        pageCount: 1
      },
      cities: {
        cities: [
          "Beijing",
          "Changsha",
          "Chengdu",
          "Hangzhou",
          "Nanjing",
          "Shanghai",
          "Tianjin",
          "Wuhan",
          "Xiamen"
        ],
        groups: [
          {
            province: null,
            cities: [
              "Beijing",
              "Shanghai",
              "Tianjin"
            ]
          },
          {
            province: "Fujian",
            cities: [
              "Xiamen"
            ]
          },
          {
            province: "Hubei",
            cities: [
              "Wuhan"
            ]
          },
          {
            province: "Hunan",
            cities: [
              "Changsha"
            ]
          },
          {
            province: "Jiangsu",
            cities: [
              "Nanjing"
            ]
          },
          {
            province: "Sichuan",
            cities: [
              "Chengdu"
            ]
          },
          {
            province: "Zhejiang",
            cities: [
              "Hangzhou"
            ]
          }
        ]
      }
    }
  },
  {
    path: "/reviews",
    data: {
      reviewsPage: {
        reviews: [
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "One-semester exchange. The language classes were excellent and the campus is genuinely beautiful, but the international office was slow with paperwork — start your visa admin early.",
            program: "Chinese Language",
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-tsinghua-canteen.jpg",
                name: "canteen.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-20T12:49:46.459163+00:00",
            enrollment_status: "exchange",
            start_year: 2024,
            end_year: 2025,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: null,
            living_cost_range: "¥4k–¥8k",
            funding_type: "school",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: "Amazing campus life, great food, easy to meet people through clubs.",
            cons: "International office response times; dorm heating is centrally controlled.",
            tags: [
              "Great food",
              "International-friendly",
              "Beautiful campus",
              "Good nightlife"
            ],
            rating_academics: 4,
            rating_campus: 5,
            rating_accommodation: null,
            rating_cost: 4,
            rating_intl_office: 3,
            rating_social: 5,
            rating_extracurricular: 4,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14",
            university_id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            user_id: null,
            rating: 4,
            text: "Great name and brilliant classmates, but the admin is a maze — every form needs three stamps and two offices. Worth it if you are patient and your Chinese is solid.",
            program: "Economics",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-18T12:49:46.459163+00:00",
            enrollment_status: "current",
            start_year: 2022,
            end_year: null,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "province",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Great food",
              "Hard bureaucracy"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 3,
            rating_intl_office: 3,
            rating_social: 4,
            rating_extracurricular: null,
            rating_career: 4
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "Studied here 2018–2022. Brutal grading but employers across Asia know the name — it opened doors everywhere. Dorms are basic; bring your own kettle and lower your expectations.",
            program: "Mechanical Engineering",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-15T12:49:46.459163+00:00",
            enrollment_status: "alumni",
            start_year: 2018,
            end_year: 2022,
            language_of_instruction: "Bilingual",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥2k–¥4k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "yes",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Hard grading",
              "Good career support"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 3,
            rating_cost: 4,
            rating_intl_office: null,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16",
            university_id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            user_id: null,
            rating: 3,
            text: "Fun semester and the food scene is unbeatable, but everything near campus is expensive and my dorm had mold. Come for the city, not the facilities.",
            program: null,
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-fudan-street.jpg",
                name: "street-food.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-fudan-river.jpg",
                name: "suzhou-creek.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-13T12:49:46.459163+00:00",
            enrollment_status: "exchange",
            start_year: 2022,
            end_year: 2023,
            language_of_instruction: "English",
            tuition_range: null,
            living_cost_range: "Over ¥8k",
            funding_type: null,
            funding_coverage: null,
            recommend: "no",
            pros: "Unbeatable food and nightlife; easy city to live in as a foreigner.",
            cons: "Dorm quality and prices near campus.",
            tags: [
              "Expensive city",
              "Good nightlife",
              "Great food"
            ],
            rating_academics: null,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: null,
            rating_social: 4,
            rating_extracurricular: 3,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T12:49:46.459163+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
            university_id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            user_id: null,
            rating: 2,
            text: "Shanghai is an amazing city but the program felt overpriced for what you get. International office support was thin when I needed visa help, and nobody warned me about the living costs.",
            program: "Journalism",
            degree_level: "Master",
            media: [],
            created_at: "2026-09-03T12:49:46.459163+00:00",
            enrollment_status: "alumni",
            start_year: 2019,
            end_year: 2021,
            language_of_instruction: "English",
            tuition_range: "¥80k–¥150k",
            living_cost_range: "Over ¥8k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "no",
            pros: null,
            cons: "Tuition plus Shanghai rent adds up fast; support for international students was limited.",
            tags: [
              "Expensive city",
              "Hard bureaucracy"
            ],
            rating_academics: 3,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: 2,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 2
          },
          {
            id: "2be276b3-0a5a-487c-84c8-3d67cca42568",
            university_id: "387a8428-7cad-40e2-a26e-8fa95d27cca4",
            user_id: null,
            rating: 5,
            text: "Xiamen University is right on the beach — literally. The architecture is gorgeous, the seafood is cheap, and the people are warm. One of the most underrated campuses in China.",
            program: "Marine Biology",
            degree_level: "Bachelor",
            media: [],
            created_at: "2025-04-10T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "3dc3b355-f9fa-436e-a857-3629ab5786f7",
            university_id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            user_id: null,
            rating: 5,
            text: "PKU has the most beautiful campus I have ever seen — Weiming Lake in autumn is unreal. The Chinese language program for international students is excellent and very affordable.",
            program: "Chinese Language",
            degree_level: "Certificate",
            media: [],
            created_at: "2025-04-02T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "7c209bbe-919d-49b6-8535-c790a22c1a5f",
            university_id: "372e17ef-cb93-40e7-a94a-a9d977983153",
            user_id: null,
            rating: 5,
            text: "Wuhan University during cherry blossom season is one of the most beautiful places on earth. The sociology department is very welcoming to international researchers.",
            program: "Sociology",
            degree_level: "PhD",
            media: [],
            created_at: "2025-03-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "91282606-c626-4b43-a3c4-3788e628f22c",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "5695352d-f624-4312-b7ff-2cf8febb2be1",
            university_id: "47a6670e-bc06-48ea-99b9-71d76b804215",
            user_id: null,
            rating: 4,
            text: "Nanjing University has a strong liberal arts tradition. The history department is fantastic and the city of Nanjing is rich in culture. Cost of living is much lower than Beijing or Shanghai.",
            program: "History",
            degree_level: "PhD",
            media: [],
            created_at: "2025-03-05T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "5d08ad83-2c87-4ec3-9817-1dd7b643fa5a",
            university_id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            user_id: null,
            rating: 4,
            text: "SJTU has a massive, modern campus in Minhang. The engineering labs are top-notch. Commute to downtown Shanghai is long but the campus itself has everything you need.",
            program: "Mechanical Engineering",
            degree_level: "Master",
            media: [],
            created_at: "2025-02-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "243f2ab9-402f-47ae-b2a7-ba4b7cf58af9",
            university_id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            user_id: null,
            rating: 4,
            text: "Shanghai life is unbeatable. Fudan has strong international programs and the career fairs are well-connected. Cafeteria food could be better but there are cheap eats everywhere nearby.",
            program: "International Relations",
            degree_level: "Bachelor",
            media: [],
            created_at: "2025-02-11T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "10729a6a-b283-42aa-833e-11b61ff9612b",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "Great academics, but the workload is no joke. Be prepared to study hard. The international office was helpful with my visa extension though.",
            program: "Environmental Engineering",
            degree_level: "PhD",
            media: [],
            created_at: "2025-01-22T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "4efa532b-1b24-467a-bf2a-dd785cb31421",
            university_id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "618992e3-3580-4afe-bb7a-d86832cfa8f6",
            university_id: "a548ce74-f26c-4649-95fb-2ab3ad53f96b",
            user_id: null,
            rating: 3,
            text: "Sichuan University has good medical programs but the international student support was hit or miss. Chengdu itself is amazing though — the food scene is incredible and rent is very affordable.",
            program: "Clinical Medicine",
            degree_level: "Bachelor",
            media: [],
            created_at: "2024-12-20T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          }
        ],
        universities: {
          "3b1b5ea6-e4b3-409f-8351-3b99015e2970": {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            slug: "tsinghua-university"
          },
          "04dc820c-7009-490b-b136-c4acf4d3460c": {
            id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            name: "Peking University",
            slug: "peking-university"
          },
          "c9cd5eee-b90e-4b87-8981-0d02bd2a3453": {
            id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            name: "Fudan University",
            slug: "fudan-university"
          },
          "b7b4db34-3a6f-4615-bfa9-7f48673683e2": {
            id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            name: "Shanghai Jiao Tong University",
            slug: "shanghai-jiao-tong-university"
          },
          "ade07bbf-a957-4e1c-b9e8-858906e9e234": {
            id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            name: "Zhejiang University",
            slug: "zhejiang-university"
          },
          "372e17ef-cb93-40e7-a94a-a9d977983153": {
            id: "372e17ef-cb93-40e7-a94a-a9d977983153",
            name: "Wuhan University",
            slug: "wuhan-university"
          },
          "a548ce74-f26c-4649-95fb-2ab3ad53f96b": {
            id: "a548ce74-f26c-4649-95fb-2ab3ad53f96b",
            name: "Sichuan University",
            slug: "sichuan-university"
          },
          "387a8428-7cad-40e2-a26e-8fa95d27cca4": {
            id: "387a8428-7cad-40e2-a26e-8fa95d27cca4",
            name: "Xiamen University",
            slug: "xiamen-university"
          },
          "47a6670e-bc06-48ea-99b9-71d76b804215": {
            id: "47a6670e-bc06-48ea-99b9-71d76b804215",
            name: "Nanjing University",
            slug: "nanjing-university"
          }
        },
        authors: {}
      }
    }
  },
  {
    path: "/city/beijing",
    data: {
      cityPage: {
        city: "Beijing",
        universities: [
          {
            id: "8756f4c8-0702-4611-be81-a43ee2b994c1",
            name: "Beihang University",
            name_zh: "北京航空航天大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "stem",
            slug: "beihang-university",
            slug_aliases: [
              "buaa"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/22403670.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://ev.buaa.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/beihang-university",
              shanghai_national: 11
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "04dc820c-7009-490b-b136-c4acf4d3460c",
            name: "Peking University",
            name_zh: "北京大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "peking-university",
            slug_aliases: [
              "peking"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/86350223.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://english.pku.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/peking-university",
              shanghai_national: 2
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          }
        ],
        reviewCount: 7
      }
    }
  },
  {
    path: "/city/shanghai",
    data: {
      cityPage: {
        city: "Shanghai",
        universities: [
          {
            id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          }
        ],
        reviewCount: 4
      }
    }
  },
  {
    path: "/program/computer-science",
    data: {
      hubPage: {
        kind: "program",
        hub: {
          slug: "computer-science",
          label: "Computer Science & IT",
          blurb: "CS, software engineering, AI and data programs reviewed by international students.",
          aliases: [
            "computer science",
            "cs",
            "computer science & technology",
            "software engineering",
            "information technology",
            "artificial intelligence",
            "ai",
            "data science",
            "big data",
            "machine learning",
            "cyber security",
            "information security"
          ]
        },
        universities: [
          {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          }
        ],
        reviews: [
          {
            id: "91282606-c626-4b43-a3c4-3788e628f22c",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "4efa532b-1b24-467a-bf2a-dd785cb31421",
            university_id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T12:49:46.459163+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          }
        ],
        authors: {}
      }
    }
  },
  {
    path: "/degree/master",
    data: {
      hubPage: {
        kind: "degree",
        hub: {
          slug: "master",
          label: "Master's Programs",
          blurb: "Postgraduate taught and research masters reviewed by students.",
          aliases: [
            "master",
            "masters",
            "master's",
            "postgraduate",
            "ma",
            "msc",
            "meng"
          ]
        },
        universities: [
          {
            id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            name: "Fudan University",
            name_zh: "复旦大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "fudan-university",
            slug_aliases: [
              "fudan"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/28312850.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.fudan.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/fudan-university",
              shanghai_national: 5
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            name: "Shanghai Jiao Tong University",
            name_zh: "上海交通大学",
            city: "Shanghai",
            country: "China",
            province: "Shanghai",
            uni_category: "comprehensive",
            slug: "shanghai-jiao-tong-university",
            slug_aliases: [
              "sjtu"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27403919.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://en.sjtu.edu.cn/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/shanghai-jiao-tong-university",
              shanghai_national: 4
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            name: "Tsinghua University",
            name_zh: "清华大学",
            city: "Beijing",
            country: "China",
            province: "Beijing",
            uni_category: "comprehensive",
            slug: "tsinghua-university",
            slug_aliases: [
              "tsinghua"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.tsinghua.edu.cn/en/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
              shanghai_national: 1
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          },
          {
            id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            name: "Zhejiang University",
            name_zh: "浙江大学",
            city: "Hangzhou",
            country: "China",
            province: "Zhejiang",
            uni_category: "comprehensive",
            slug: "zhejiang-university",
            slug_aliases: [
              "zhejiang",
              "zju"
            ],
            logo_url: "https://www.shanghairanking.cn/_uni/logo/88311656.png",
            is_verified: false,
            uni_type: "public",
            languages_of_instruction: [
              "Chinese",
              "English"
            ],
            website: "https://www.zju.edu.cn/english/",
            rankings: {
              shanghai_url: "https://www.shanghairanking.cn/institution/zhejiang-university",
              shanghai_national: 3
            },
            created_at: "2026-09-24T12:49:46.459163+00:00"
          }
        ],
        reviews: [
          {
            id: "91282606-c626-4b43-a3c4-3788e628f22c",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "4efa532b-1b24-467a-bf2a-dd785cb31421",
            university_id: "ade07bbf-a957-4e1c-b9e8-858906e9e234",
            user_id: null,
            rating: 4,
            text: "Zhejiang has a huge campus in Hangzhou with great facilities. The CS program is competitive but the professors are approachable. Close to Alibaba HQ which means good internship opportunities.",
            program: "Data Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-01-15T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "5d08ad83-2c87-4ec3-9817-1dd7b643fa5a",
            university_id: "b7b4db34-3a6f-4615-bfa9-7f48673683e2",
            user_id: null,
            rating: 4,
            text: "SJTU has a massive, modern campus in Minhang. The engineering labs are top-notch. Commute to downtown Shanghai is long but the campus itself has everything you need.",
            program: "Mechanical Engineering",
            degree_level: "Master",
            media: [],
            created_at: "2025-02-28T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T12:49:46.459163+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15",
            university_id: "c9cd5eee-b90e-4b87-8981-0d02bd2a3453",
            user_id: null,
            rating: 2,
            text: "Shanghai is an amazing city but the program felt overpriced for what you get. International office support was thin when I needed visa help, and nobody warned me about the living costs.",
            program: "Journalism",
            degree_level: "Master",
            media: [],
            created_at: "2026-09-03T12:49:46.459163+00:00",
            enrollment_status: "alumni",
            start_year: 2019,
            end_year: 2021,
            language_of_instruction: "English",
            tuition_range: "¥80k–¥150k",
            living_cost_range: "Over ¥8k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "no",
            pros: null,
            cons: "Tuition plus Shanghai rent adds up fast; support for international students was limited.",
            tags: [
              "Expensive city",
              "Hard bureaucracy"
            ],
            rating_academics: 3,
            rating_campus: 4,
            rating_accommodation: 2,
            rating_cost: 1,
            rating_intl_office: 2,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 2
          }
        ],
        authors: {}
      }
    }
  },
  {
    path: "/about",
    data: {}
  },
  {
    path: "/contact",
    data: {}
  },
  {
    path: "/editorial-policy",
    data: {}
  },
  {
    path: "/how-we-verify",
    data: {}
  },
  {
    path: "/review-guidelines",
    data: {}
  },
  {
    path: "/data-sources",
    data: {}
  },
  {
    path: "/privacy",
    data: {}
  },
  {
    path: "/terms",
    data: {}
  },
  {
    path: "/disclaimer",
    data: {}
  },
  {
    path: "/report",
    data: {}
  },
  {
    path: "/university/tsinghua-university",
    data: {
      universityPage: {
        university: {
          id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
          name: "Tsinghua University",
          name_zh: "清华大学",
          city: "Beijing",
          country: "China",
          province: "Beijing",
          uni_category: "comprehensive",
          slug: "tsinghua-university",
          slug_aliases: [
            "tsinghua"
          ],
          logo_url: "https://www.shanghairanking.cn/_uni/logo/27532357.png",
          is_verified: false,
          uni_type: "public",
          languages_of_instruction: [
            "Chinese",
            "English"
          ],
          website: "https://www.tsinghua.edu.cn/en/",
          rankings: {
            shanghai_url: "https://www.shanghairanking.cn/institution/tsinghua-university",
            shanghai_national: 1
          },
          created_at: "2026-09-24T12:49:46.459163+00:00"
        },
        reviews: [
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "One-semester exchange. The language classes were excellent and the campus is genuinely beautiful, but the international office was slow with paperwork — start your visa admin early.",
            program: "Chinese Language",
            degree_level: "Exchange",
            media: [
              {
                url: "/media/demo/trc-tsinghua-canteen.jpg",
                name: "canteen.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-20T12:49:46.459163+00:00",
            enrollment_status: "exchange",
            start_year: 2024,
            end_year: 2025,
            language_of_instruction: "Chinese (Mandarin)",
            tuition_range: null,
            living_cost_range: "¥4k–¥8k",
            funding_type: "school",
            funding_coverage: "partial",
            recommend: "maybe",
            pros: "Amazing campus life, great food, easy to meet people through clubs.",
            cons: "International office response times; dorm heating is centrally controlled.",
            tags: [
              "Great food",
              "International-friendly",
              "Beautiful campus",
              "Good nightlife"
            ],
            rating_academics: 4,
            rating_campus: 5,
            rating_accommodation: null,
            rating_cost: 4,
            rating_intl_office: 3,
            rating_social: 5,
            rating_extracurricular: 4,
            rating_career: null
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "Studied here 2018–2022. Brutal grading but employers across Asia know the name — it opened doors everywhere. Dorms are basic; bring your own kettle and lower your expectations.",
            program: "Mechanical Engineering",
            degree_level: "Bachelor",
            media: [],
            created_at: "2026-09-15T12:49:46.459163+00:00",
            enrollment_status: "alumni",
            start_year: 2018,
            end_year: 2022,
            language_of_instruction: "Bilingual",
            tuition_range: "¥20k–¥40k",
            living_cost_range: "¥2k–¥4k",
            funding_type: "self",
            funding_coverage: null,
            recommend: "yes",
            pros: null,
            cons: null,
            tags: [
              "Strong academics",
              "Hard grading",
              "Good career support"
            ],
            rating_academics: 5,
            rating_campus: 4,
            rating_accommodation: 3,
            rating_cost: 4,
            rating_intl_office: null,
            rating_social: 3,
            rating_extracurricular: null,
            rating_career: 5
          },
          {
            id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "Two years into my master's and the research access here is unreal — my lab publishes constantly and professors actually reply to emails. The workload is heavy but the campus feels like its own small city.",
            program: "Computer Science",
            degree_level: "Master",
            media: [
              {
                url: "/media/demo/trc-tsinghua-quad.jpg",
                name: "main-quad.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lib.jpg",
                name: "library.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-dorm.jpg",
                name: "dorm.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-gate.jpg",
                name: "gate.jpg",
                type: "image"
              },
              {
                url: "/media/demo/trc-tsinghua-lake.jpg",
                name: "lake.jpg",
                type: "image"
              }
            ],
            created_at: "2026-09-08T12:49:46.459163+00:00",
            enrollment_status: "current",
            start_year: 2023,
            end_year: null,
            language_of_instruction: "English",
            tuition_range: "¥40k–¥80k",
            living_cost_range: "¥4k–¥8k",
            funding_type: "csc",
            funding_coverage: "full",
            recommend: "yes",
            pros: "World-class labs and libraries. CSC funding covered tuition and a decent stipend.",
            cons: "Dorms are dated for the price, and course registration for international students is confusing.",
            tags: [
              "Strong academics",
              "Research opportunities",
              "Beautiful campus",
              "Active clubs"
            ],
            rating_academics: 5,
            rating_campus: 5,
            rating_accommodation: 3,
            rating_cost: 3,
            rating_intl_office: 4,
            rating_social: 4,
            rating_extracurricular: 5,
            rating_career: 5
          },
          {
            id: "91282606-c626-4b43-a3c4-3788e628f22c",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 5,
            text: "The campus is stunning and the engineering faculty is world-class. Professors genuinely care about international students and there are tons of English-taught programs. The dorm situation is tight but manageable.",
            program: "Computer Science",
            degree_level: "Master",
            media: [],
            created_at: "2025-03-14T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          },
          {
            id: "10729a6a-b283-42aa-833e-11b61ff9612b",
            university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
            user_id: null,
            rating: 4,
            text: "Great academics, but the workload is no joke. Be prepared to study hard. The international office was helpful with my visa extension though.",
            program: "Environmental Engineering",
            degree_level: "PhD",
            media: [],
            created_at: "2025-01-22T00:00:00+00:00",
            enrollment_status: null,
            start_year: null,
            end_year: null,
            language_of_instruction: null,
            tuition_range: null,
            living_cost_range: null,
            funding_type: null,
            funding_coverage: null,
            recommend: null,
            pros: null,
            cons: null,
            tags: [],
            rating_academics: null,
            rating_campus: null,
            rating_accommodation: null,
            rating_cost: null,
            rating_intl_office: null,
            rating_social: null,
            rating_extracurricular: null,
            rating_career: null
          }
        ],
        authors: {},
        stats: {
          university_id: "3b1b5ea6-e4b3-409f-8351-3b99015e2970",
          avg_rating: 4.4,
          review_count: 5,
          has_verified_review: false,
          recommend_yes_count: 2,
          recommend_maybe_count: 1,
          recommend_no_count: 0,
          updated_at: "2026-09-24T12:49:46.459163+00:00"
        }
      }
    }
  }
] as const
