#!/usr/bin/env node
// build_university_merge.mjs — merge the scraped 软科 list into our seed
// dataset and emit supabase/seed_merge.sql.
//
//   node scripts/build_university_merge.mjs [--year 2026]
//
// Field policy (decided from scripts/audit_university_merge.mjs):
//   THEIRS wins  → name, name_zh, rankings{shanghai_national,shanghai_url},
//                  logo_url only when ours is a broken shanghairanking id
//   OURS wins    → slug (canonical), city, country, website, uni_type, langs
//   BOTH kept    → slugs: scraped univUp becomes a slug_alias; duplicate
//                  rows across our two seed files collapse via DO blocks
//                  (canonical = the seed.sql row — it carries richer data).

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  BASE,
  fetchUnivData,
  parseSeedRows,
  matchUniversities,
  sqlString,
  PROVINCE_EN,
  CATEGORY_EN,
  INDICATOR_EN,
} from './lib/shanghairanking.mjs'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const YEAR = process.argv.includes('--year')
  ? process.argv[process.argv.indexOf('--year') + 1]
  : '2026'
const OUT = resolve(ROOT, 'supabase/seed_merge.sql')

const { univData, indList, listUrl } = await fetchUnivData(YEAR)
const indCodeToName = new Map(indList.map((i) => [String(i.code), i.nameCn]))
const indCodeToEn = (code) => INDICATOR_EN[indCodeToName.get(String(code))]
const ours = parseSeedRows(ROOT)
const { matched, unmatchedTheirs } = matchUniversities(univData, ours)

// ---- internal duplicates: same school under two of our slugs --------------
// canonical = the seed.sql row (richer columns); the other becomes an alias.
const byZhAll = new Map()
const dupes = [] // { canonical, alias }
for (const r of ours) {
  const prev = byZhAll.get(r.nameZh)
  if (prev && prev.slug !== r.slug) {
    const canonical = prev.file.endsWith('seed.sql') ? prev : r
    const alias = canonical === prev ? r : prev
    dupes.push({ canonical: canonical.slug, alias: alias.slug })
  }
  byZhAll.set(r.nameZh, r)
}
const aliasToCanonical = new Map(dupes.map((d) => [d.alias, d.canonical]))

// ---- emit ------------------------------------------------------------------
const esc = sqlString
const lines = [
  `-- Generated by scripts/build_university_merge.mjs — do not hand-edit.`,
  `-- Source: ${listUrl} (软科中国大学排名 ${YEAR}, ${univData.length} schools)`,
  `-- Matched ${matched.length} of ${ours.length} seed rows; ${unmatchedTheirs.length} scraped schools not in our dataset.`,
  `-- Field policy: names/logos/rankings ← ShanghaiRanking; slug, city,`,
  `-- country, website, uni_type, languages ← ours. univUp → slug_aliases.`,
  `-- Canonical slug ← ShanghaiRanking univUp via`,
  `-- supabase/data/promote_descriptive_slugs.sql (applied after this file).`,
  ``,
]

const aliasSeen = new Map() // alias -> slug (collision check)
let logoFixes = 0
for (const m of matched) {
  const canonical = aliasToCanonical.get(m.ours.slug) ?? m.ours.slug
  const rank = /^(\d+)/.exec(String(m.theirs.ranking))?.[1]
  if (!rank) continue

  const score = Number.parseFloat(m.theirs.score)
  const rankings = {
    shanghai_national: Number(rank),
    shanghai_url: `${BASE}/institution/${m.theirs.univUp}`,
    ...(Number.isFinite(score) && score > 0 ? { shanghai_score: score } : {}),
    // prestige tags (985 / 211 / 双一流) — most rows have none
    ...(m.theirs.univTags?.length ? { shanghai_tags: m.theirs.univTags } : {}),
    // 软科 10-dimension indicator sub-scores — only top ~100 schools get them
    ...(m.theirs.indData && Object.values(m.theirs.indData).some((v) => v !== '')
      ? {
          // normalize year-varying codes (788…) to stable EN keys via indList
          shanghai_indicators: Object.fromEntries(
            Object.entries(m.theirs.indData)
              .filter(([, v]) => v !== '')
              .map(([code, v]) => [indCodeToEn(code) ?? code, Number.parseFloat(v)])
          ),
        }
      : {}),
  }
  const setParts = [
    `name = ${esc(m.theirs.univNameEn)}`,
    `name_zh = ${esc(m.theirs.univNameCn)}`,
    `rankings = rankings || ${esc(JSON.stringify(rankings))}::jsonb`,
    `slug_aliases = (SELECT array_agg(DISTINCT x) FROM unnest(array_cat(slug_aliases, '{${m.theirs.univUp}}')) x)`,
  ]
  const provEn = PROVINCE_EN[m.theirs.province]
  if (provEn) setParts.push(`province = ${esc(provEn)}`)
  // the 软科 national list only ranks mainland schools
  setParts.push(`country = COALESCE(country, 'China')`)
  const catEn = CATEGORY_EN[m.theirs.univCategory]
  if (catEn) setParts.push(`uni_category = ${esc(catEn)}`)
  // broken logo ids (ours ends in 00 / different from theirs) → take theirs
  if (m.ours.logoId && m.logoId && m.ours.logoId !== m.logoId) {
    setParts.push(`logo_url = ${esc(`${BASE}/_uni/${m.theirs.univLogo}`)}`)
    logoFixes++
  }
  lines.push(`UPDATE universities SET ${setParts.join(',\n  ')} WHERE slug = ${esc(canonical)} OR ${esc(canonical)} = ANY(slug_aliases);`)

  if (aliasSeen.has(m.theirs.univUp) && aliasSeen.get(m.theirs.univUp) !== canonical)
    console.warn(`ALIAS COLLISION: ${m.theirs.univUp} claimed by ${aliasSeen.get(m.theirs.univUp)} and ${canonical}`)
  aliasSeen.set(m.theirs.univUp, canonical)
}

// collapse duplicate rows (guarded — no-op in envs where only one side exists)
// survivor refs are alias-aware (safe after slug promotion); loser refs and
// the DELETE stay exact-slug — an alias-aware DELETE would remove the survivor.
for (const d of dupes) {
  lines.push(`
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM universities WHERE slug = '${d.canonical}' OR '${d.canonical}' = ANY(slug_aliases))
     AND EXISTS (SELECT 1 FROM universities WHERE slug = '${d.alias}') THEN
    UPDATE universities
      SET slug_aliases = (SELECT array_agg(DISTINCT x) FROM unnest(array_cat(slug_aliases, '{${d.alias}}')) x),
          logo_url = CASE WHEN logo_url ~ '^https://www\\.shanghairanking\\.cn/' THEN logo_url
                          ELSE COALESCE(NULLIF((SELECT l.logo_url FROM universities l WHERE l.slug = '${d.alias}'), ''), logo_url) END
      WHERE slug = '${d.canonical}' OR '${d.canonical}' = ANY(slug_aliases);
    UPDATE reviews SET university_id = (SELECT id FROM universities WHERE slug = '${d.canonical}' OR '${d.canonical}' = ANY(slug_aliases))
      WHERE university_id = (SELECT id FROM universities WHERE slug = '${d.alias}');
    DELETE FROM universities WHERE slug = '${d.alias}';
  END IF;
END $$;`)
}

writeFileSync(OUT, lines.join('\n') + '\n')
console.log(`wrote ${OUT}`)
console.log(`updates: ${matched.length} · logo fixes: ${logoFixes} · dedupe blocks: ${dupes.length}`)
dupes.forEach((d) => console.log(`  dedupe: ${d.alias} → ${d.canonical}`))
