#!/usr/bin/env node
// scrape_shanghairanking.mjs — pull the ShanghaiRanking (软科中国大学排名)
// national list and emit SQL that fills universities.rankings for every
// matched school.
//
//   node scripts/scrape_shanghairanking.mjs [--year 2026] [--out supabase/seed_rankings.sql]
//
// How it works: the ranking page is Nuxt SSR. Its sibling `payload.js`
// (Referer-gated) contains the full 589-row list as structured data —
// no HTML table scraping needed. Matching to our rows is by the logo id
// (our seed logo_urls are shanghairanking.cn/_uni/logo/<id>.png and the
// payload carries the same id in univLogo), falling back to name_zh /
// English name equality.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
const argVal = (flag, fallback) => {
  const i = args.indexOf(flag)
  return i >= 0 ? args[i + 1] : fallback
}
const YEAR = argVal('--year', '2026')
const OUT = resolve(ROOT, argVal('--out', 'supabase/seed_rankings.sql'))
const BASE = 'https://www.shanghairanking.cn'
const LIST_URL = `${BASE}/rankings/bcur/${YEAR}`

const HEADERS = {
  'user-agent':
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
  'accept-language': 'zh-CN,zh;q=0.9',
}

async function fetchText(url, referer) {
  const res = await fetch(url, {
    headers: referer ? { ...HEADERS, referer } : HEADERS,
  })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`)
  return res.text()
}

// ---- 1. list page → payload.js path ---------------------------------------
const html = await fetchText(LIST_URL)
const payloadPath = html.match(/(\/_nuxt\/static\/[^"]+\/payload\.js)/)?.[1]
if (!payloadPath) throw new Error('payload.js URL not found in list page HTML')

// ---- 2. payload (Referer ACL) → eval JSONP → univData ---------------------
const payloadSrc = await fetchText(`${BASE}${payloadPath}`, LIST_URL)
let captured
const __NUXT_JSONP__ = (_path, data) => {
  captured = data
}
eval(payloadSrc) // eslint-disable-line no-eval — trusted vendor payload
const univData = captured?.data?.[0]?.univData
if (!Array.isArray(univData) || univData.length < 100)
  throw new Error(`univData missing/short (got ${univData?.length})`)

// ---- 3. our universities from the seed files ------------------------------
// Row shape in seed_universities.sql / seed.sql VALUES:
//   ('Name', '中文名', 'City', 'slug', 'logo_url', false, ...)
const seedRows = []
const rowRe =
  /\('((?:[^'\\]|\\.|'')*)',\s*'((?:[^'\\]|\\.|'')*)',\s*'((?:[^'\\]|\\.|'')*)',\s*'((?:[^'\\]|\\.|'')*)',\s*'((?:[^'\\]|\\.|'')*)'/g
const unescape = (s) => s.replace(/''/g, "'").replace(/\\'/g, "'")
for (const file of ['supabase/seed_universities.sql', 'supabase/seed.sql']) {
  const sql = readFileSync(join(ROOT, file), 'utf8')
  // only parse INSERTs that target universities
  for (const stmt of sql.split(/;(?=\s*(?:--|INSERT|$))/g)) {
    if (!/INSERT INTO universities/i.test(stmt)) continue
    for (const m of stmt.matchAll(rowRe)) {
      seedRows.push({
        name: unescape(m[1]),
        nameZh: unescape(m[2]),
        slug: unescape(m[4]),
        logoId: /logo\/(\d+)\.png/.exec(m[5])?.[1] ?? null,
      })
    }
  }
}
console.log(`shanghairanking rows: ${univData.length} · our seed rows: ${seedRows.length}`)

// ---- 4. match --------------------------------------------------------------
const byLogo = new Map()
const byZh = new Map()
const byEn = new Map()
for (const r of seedRows) {
  if (r.logoId) byLogo.set(r.logoId, r)
  byZh.set(r.nameZh, r)
  byEn.set(r.name.toLowerCase(), r)
}

const matched = []
const ourUnmatched = new Set(seedRows.map((r) => r.slug))
for (const u of univData) {
  const logoId = /logo\/(\d+)\.png/.exec(u.univLogo ?? '')?.[1]
  const hit =
    (logoId && byLogo.get(logoId)) ||
    byZh.get(u.univNameCn) ||
    byEn.get((u.univNameEn ?? '').toLowerCase())
  if (!hit) continue
  const rank = /^(\d+)/.exec(String(u.ranking))?.[1]
  if (!rank) continue
  matched.push({
    slug: hit.slug,
    name: u.univNameCn,
    rank: Number(rank),
    url: `${BASE}/institution/${u.univUp}`,
    via: logoId && byLogo.get(logoId) === hit ? 'logo' : byZh.get(u.univNameCn) === hit ? 'name_zh' : 'name_en',
  })
  ourUnmatched.delete(hit.slug)
}

// dedupe slugs (same uni can appear in both seed files under one slug)
const bySlug = new Map(matched.map((m) => [m.slug, m]))

// ---- 5. emit SQL -----------------------------------------------------------
const lines = [
  `-- Generated by scripts/scrape_shanghairanking.mjs — do not hand-edit.`,
  `-- Source: ${LIST_URL} (软科中国大学排名 ${YEAR}, ${univData.length} schools)`,
  `-- Matched ${bySlug.size} of our ${new Set(seedRows.map((r) => r.slug)).size} seeded universities.`,
  ``,
]
for (const m of [...bySlug.values()].sort((a, b) => a.rank - b.rank)) {
  lines.push(
    `UPDATE universities SET rankings = jsonb_build_object('shanghai_national', ${m.rank}, 'shanghai_url', '${m.url}') WHERE slug = '${m.slug}';`
  )
}
writeFileSync(OUT, lines.join('\n') + '\n')

console.log(`matched: ${bySlug.size} (logo: ${matched.filter((m) => m.via === 'logo').length}, name_zh: ${matched.filter((m) => m.via === 'name_zh').length}, name_en: ${matched.filter((m) => m.via === 'name_en').length})`)
console.log(`wrote ${OUT}`)
if (ourUnmatched.size) {
  console.log(`unmatched ours (${ourUnmatched.size}):`, [...ourUnmatched].slice(0, 20).join(', '), ourUnmatched.size > 20 ? '…' : '')
}
