-- 034_null_pseudo_uni_cities.sql
--
-- universities.city was seeded from a province-granular source: for ~90% of
-- rows the "city" is actually the province name (Jiangsu, Shandong, …).
-- Municipalities (Beijing/Shanghai/Tianjin/Chongqing) legitimately keep
-- city = province.
--
-- 1. Drop NOT NULL so city can be absent.
-- 2. Backfill province from the canonical city->province map (generated from
--    frontend/src/lib/chinaDivisions.ts). Needed for envs where `province` is
--    fresh from migration 030 and never populated — a prod apply would
--    otherwise leave every row with no location at all. `AND province IS NULL`
--    makes this a no-op where province is already set (staging/local).
--    Homophone cities resolve to the dominant reading (Suzhou -> Jiangsu);
--    'Yulin' (Guangxi vs Shaanxi) is excluded as genuinely ambiguous.
-- 3. NULL the pseudo-cities so `city` means "city" again — display surfaces
--    fall back to province.

ALTER TABLE public.universities
  ALTER COLUMN city DROP NOT NULL;

UPDATE public.universities u
SET province = m.prov
FROM (VALUES
    ('Aksu', 'Xinjiang'),
    ('Alar', 'Xinjiang'),
    ('Altay', 'Xinjiang'),
    ('Alxa', 'Inner Mongolia'),
    ('Anhui', 'Anhui'),
    ('Ankang', 'Shaanxi'),
    ('Anqing', 'Anhui'),
    ('Anshan', 'Liaoning'),
    ('Anshun', 'Guizhou'),
    ('Anyang', 'Henan'),
    ('Baicheng', 'Jilin'),
    ('Baise', 'Guangxi'),
    ('Baisha', 'Hainan'),
    ('Baishan', 'Jilin'),
    ('Baiyin', 'Gansu'),
    ('Baoding', 'Hebei'),
    ('Baoji', 'Shaanxi'),
    ('Baoshan', 'Yunnan'),
    ('Baoting', 'Hainan'),
    ('Baotou', 'Inner Mongolia'),
    ('Bayannur', 'Inner Mongolia'),
    ('Bayingolin', 'Xinjiang'),
    ('Bazhong', 'Sichuan'),
    ('Beihai', 'Guangxi'),
    ('Beijing', 'Beijing'),
    ('Beitun', 'Xinjiang'),
    ('Bengbu', 'Anhui'),
    ('Benxi', 'Liaoning'),
    ('Bijie', 'Guizhou'),
    ('Binzhou', 'Shandong'),
    ('Bortala', 'Xinjiang'),
    ('Bozhou', 'Anhui'),
    ('Cangzhou', 'Hebei'),
    ('Changchun', 'Jilin'),
    ('Changde', 'Hunan'),
    ('Changji', 'Xinjiang'),
    ('Changjiang', 'Hainan'),
    ('Changsha', 'Hunan'),
    ('Changzhi', 'Shanxi'),
    ('Changzhou', 'Jiangsu'),
    ('Chaoyang', 'Liaoning'),
    ('Chaozhou', 'Guangdong'),
    ('Chengde', 'Hebei'),
    ('Chengdu', 'Sichuan'),
    ('Chengmai', 'Hainan'),
    ('Chenzhou', 'Hunan'),
    ('Chifeng', 'Inner Mongolia'),
    ('Chizhou', 'Anhui'),
    ('Chongqing', 'Chongqing'),
    ('Chongzuo', 'Guangxi'),
    ('Chuxiong', 'Yunnan'),
    ('Chuzhou', 'Anhui'),
    ('Dali', 'Yunnan'),
    ('Dalian', 'Liaoning'),
    ('Dandong', 'Liaoning'),
    ('Danzhou', 'Hainan'),
    ('Daqing', 'Heilongjiang'),
    ('Datong', 'Shanxi'),
    ('Daxing''anling', 'Heilongjiang'),
    ('Dazhou', 'Sichuan'),
    ('Dehong', 'Yunnan'),
    ('Deyang', 'Sichuan'),
    ('Dezhou', 'Shandong'),
    ('Dingan', 'Hainan'),
    ('Dingxi', 'Gansu'),
    ('Diqing', 'Yunnan'),
    ('Dongfang', 'Hainan'),
    ('Dongguan', 'Guangdong'),
    ('Dongying', 'Shandong'),
    ('Enshi', 'Hubei'),
    ('Ezhou', 'Hubei'),
    ('Fangchenggang', 'Guangxi'),
    ('Foshan', 'Guangdong'),
    ('Fujian', 'Fujian'),
    ('Fushun', 'Liaoning'),
    ('Fuxin', 'Liaoning'),
    ('Fuyang', 'Anhui'),
    ('Fuzhou', 'Fujian'),
    ('Gannan', 'Gansu'),
    ('Gansu', 'Gansu'),
    ('Ganzhou', 'Jiangxi'),
    ('Garze', 'Sichuan'),
    ('Golog', 'Qinghai'),
    ('Guangan', 'Sichuan'),
    ('Guangdong', 'Guangdong'),
    ('Guangxi', 'Guangxi'),
    ('Guangyuan', 'Sichuan'),
    ('Guangzhou', 'Guangdong'),
    ('Guigang', 'Guangxi'),
    ('Guilin', 'Guangxi'),
    ('Guiyang', 'Guizhou'),
    ('Guizhou', 'Guizhou'),
    ('Guyuan', 'Ningxia'),
    ('Haibei', 'Qinghai'),
    ('Haidong', 'Qinghai'),
    ('Haikou', 'Hainan'),
    ('Hainan', 'Hainan'),
    ('Haixi', 'Qinghai'),
    ('Hami', 'Xinjiang'),
    ('Handan', 'Hebei'),
    ('Hangzhou', 'Zhejiang'),
    ('Hanzhong', 'Shaanxi'),
    ('Harbin', 'Heilongjiang'),
    ('Hebei', 'Hebei'),
    ('Hebi', 'Henan'),
    ('Hechi', 'Guangxi'),
    ('Hefei', 'Anhui'),
    ('Hegang', 'Heilongjiang'),
    ('Heihe', 'Heilongjiang'),
    ('Heilongjiang', 'Heilongjiang'),
    ('Henan', 'Henan'),
    ('Hengshui', 'Hebei'),
    ('Hengyang', 'Hunan'),
    ('Heyuan', 'Guangdong'),
    ('Heze', 'Shandong'),
    ('Hezhou', 'Guangxi'),
    ('Hinggan', 'Inner Mongolia'),
    ('Hohhot', 'Inner Mongolia'),
    ('Honghe', 'Yunnan'),
    ('Hotan', 'Xinjiang'),
    ('Huai''an', 'Jiangsu'),
    ('Huaibei', 'Anhui'),
    ('Huaihua', 'Hunan'),
    ('Huainan', 'Anhui'),
    ('Huanggang', 'Hubei'),
    ('Huangnan', 'Qinghai'),
    ('Huangshan', 'Anhui'),
    ('Huangshi', 'Hubei'),
    ('Hubei', 'Hubei'),
    ('Huizhou', 'Guangdong'),
    ('Huludao', 'Liaoning'),
    ('Hulunbuir', 'Inner Mongolia'),
    ('Hunan', 'Hunan'),
    ('Huyanghe', 'Xinjiang'),
    ('Huzhou', 'Zhejiang'),
    ('Ili', 'Xinjiang'),
    ('Inner Mongolia', 'Inner Mongolia'),
    ('Ji''an', 'Jiangxi'),
    ('Jiamusi', 'Heilongjiang'),
    ('Jiangmen', 'Guangdong'),
    ('Jiangsu', 'Jiangsu'),
    ('Jiangxi', 'Jiangxi'),
    ('Jiaozuo', 'Henan'),
    ('Jiaxing', 'Zhejiang'),
    ('Jiayuguan', 'Gansu'),
    ('Jieyang', 'Guangdong'),
    ('Jilin', 'Jilin'),
    ('Jinan', 'Shandong'),
    ('Jinchang', 'Gansu'),
    ('Jincheng', 'Shanxi'),
    ('Jingdezhen', 'Jiangxi'),
    ('Jingmen', 'Hubei'),
    ('Jingzhou', 'Hubei'),
    ('Jinhua', 'Zhejiang'),
    ('Jining', 'Shandong'),
    ('Jinzhong', 'Shanxi'),
    ('Jinzhou', 'Liaoning'),
    ('Jiujiang', 'Jiangxi'),
    ('Jiuquan', 'Gansu'),
    ('Jixi', 'Heilongjiang'),
    ('Jiyuan', 'Henan'),
    ('Kaifeng', 'Henan'),
    ('Karamay', 'Xinjiang'),
    ('Kashgar', 'Xinjiang'),
    ('Kizilsu', 'Xinjiang'),
    ('Kokdala', 'Xinjiang'),
    ('Kunming', 'Yunnan'),
    ('Kunyu', 'Xinjiang'),
    ('Laibin', 'Guangxi'),
    ('Langfang', 'Hebei'),
    ('Lanzhou', 'Gansu'),
    ('Ledong', 'Hainan'),
    ('Leshan', 'Sichuan'),
    ('Lhasa', 'Tibet'),
    ('Liangshan', 'Sichuan'),
    ('Lianyungang', 'Jiangsu'),
    ('Liaocheng', 'Shandong'),
    ('Liaoning', 'Liaoning'),
    ('Liaoyang', 'Liaoning'),
    ('Liaoyuan', 'Jilin'),
    ('Lijiang', 'Yunnan'),
    ('Lincang', 'Yunnan'),
    ('Linfen', 'Shanxi'),
    ('Lingao', 'Hainan'),
    ('Lingshui', 'Hainan'),
    ('Linxia', 'Gansu'),
    ('Linyi', 'Shandong'),
    ('Lishui', 'Zhejiang'),
    ('Liupanshui', 'Guizhou'),
    ('Liuzhou', 'Guangxi'),
    ('Longnan', 'Gansu'),
    ('Longyan', 'Fujian'),
    ('Loudi', 'Hunan'),
    ('Lu''an', 'Anhui'),
    ('Luohe', 'Henan'),
    ('Luoyang', 'Henan'),
    ('Luzhou', 'Sichuan'),
    ('Lvliang', 'Shanxi'),
    ('Maanshan', 'Anhui'),
    ('Maoming', 'Guangdong'),
    ('Meishan', 'Sichuan'),
    ('Meizhou', 'Guangdong'),
    ('Mianyang', 'Sichuan'),
    ('Mudanjiang', 'Heilongjiang'),
    ('Nagqu', 'Tibet'),
    ('Nanchang', 'Jiangxi'),
    ('Nanchong', 'Sichuan'),
    ('Nanjing', 'Jiangsu'),
    ('Nanning', 'Guangxi'),
    ('Nanping', 'Fujian'),
    ('Nantong', 'Jiangsu'),
    ('Nanyang', 'Henan'),
    ('Neijiang', 'Sichuan'),
    ('Ngari', 'Tibet'),
    ('Ngawa', 'Sichuan'),
    ('Ningbo', 'Zhejiang'),
    ('Ningde', 'Fujian'),
    ('Ningxia', 'Ningxia'),
    ('Nujiang', 'Yunnan'),
    ('Nyingchi', 'Tibet'),
    ('Ordos', 'Inner Mongolia'),
    ('Panjin', 'Liaoning'),
    ('Panzhihua', 'Sichuan'),
    ('Pingdingshan', 'Henan'),
    ('Pingliang', 'Gansu'),
    ('Pingxiang', 'Jiangxi'),
    ('Puer', 'Yunnan'),
    ('Putian', 'Fujian'),
    ('Puyang', 'Henan'),
    ('Qamdo', 'Tibet'),
    ('Qiandongnan', 'Guizhou'),
    ('Qianjiang', 'Hubei'),
    ('Qiannan', 'Guizhou'),
    ('Qianxinan', 'Guizhou'),
    ('Qingdao', 'Shandong'),
    ('Qinghai', 'Qinghai'),
    ('Qingyang', 'Gansu'),
    ('Qingyuan', 'Guangdong'),
    ('Qinhuangdao', 'Hebei'),
    ('Qinzhou', 'Guangxi'),
    ('Qionghai', 'Hainan'),
    ('Qiongzhong', 'Hainan'),
    ('Qiqihar', 'Heilongjiang'),
    ('Qitaihe', 'Heilongjiang'),
    ('Quanzhou', 'Fujian'),
    ('Qujing', 'Yunnan'),
    ('Quzhou', 'Zhejiang'),
    ('Rizhao', 'Shandong'),
    ('Sanmenxia', 'Henan'),
    ('Sanming', 'Fujian'),
    ('Sansha', 'Hainan'),
    ('Sanya', 'Hainan'),
    ('Shaanxi', 'Shaanxi'),
    ('Shandong', 'Shandong'),
    ('Shanghai', 'Shanghai'),
    ('Shangluo', 'Shaanxi'),
    ('Shangqiu', 'Henan'),
    ('Shangrao', 'Jiangxi'),
    ('Shannan', 'Tibet'),
    ('Shantou', 'Guangdong'),
    ('Shanwei', 'Guangdong'),
    ('Shanxi', 'Shanxi'),
    ('Shaoguan', 'Guangdong'),
    ('Shaoxing', 'Zhejiang'),
    ('Shaoyang', 'Hunan'),
    ('Shennongjia', 'Hubei'),
    ('Shenyang', 'Liaoning'),
    ('Shenzhen', 'Guangdong'),
    ('Shigatse', 'Tibet'),
    ('Shihezi', 'Xinjiang'),
    ('Shijiazhuang', 'Hebei'),
    ('Shiyan', 'Hubei'),
    ('Shizuishan', 'Ningxia'),
    ('Shuanghe', 'Xinjiang'),
    ('Shuangyashan', 'Heilongjiang'),
    ('Shuozhou', 'Shanxi'),
    ('Sichuan', 'Sichuan'),
    ('Siping', 'Jilin'),
    ('Songyuan', 'Jilin'),
    ('Suihua', 'Heilongjiang'),
    ('Suining', 'Sichuan'),
    ('Suizhou', 'Hubei'),
    ('Suqian', 'Jiangsu'),
    ('Suzhou', 'Jiangsu'),
    ('Tacheng', 'Xinjiang'),
    ('Tai''an', 'Shandong'),
    ('Taiyuan', 'Shanxi'),
    ('Taizhou', 'Jiangsu'),
    ('Tangshan', 'Hebei'),
    ('Tianjin', 'Tianjin'),
    ('Tianmen', 'Hubei'),
    ('Tianshui', 'Gansu'),
    ('Tibet', 'Tibet'),
    ('Tieling', 'Liaoning'),
    ('Tiemenguan', 'Xinjiang'),
    ('Tongchuan', 'Shaanxi'),
    ('Tonghua', 'Jilin'),
    ('Tongliao', 'Inner Mongolia'),
    ('Tongling', 'Anhui'),
    ('Tongren', 'Guizhou'),
    ('Tumxuk', 'Xinjiang'),
    ('Tunchang', 'Hainan'),
    ('Turpan', 'Xinjiang'),
    ('Ulanqab', 'Inner Mongolia'),
    ('Urumqi', 'Xinjiang'),
    ('Wanning', 'Hainan'),
    ('Weifang', 'Shandong'),
    ('Weihai', 'Shandong'),
    ('Weinan', 'Shaanxi'),
    ('Wenchang', 'Hainan'),
    ('Wenshan', 'Yunnan'),
    ('Wenzhou', 'Zhejiang'),
    ('Wuhai', 'Inner Mongolia'),
    ('Wuhan', 'Hubei'),
    ('Wuhu', 'Anhui'),
    ('Wujiaqu', 'Xinjiang'),
    ('Wuwei', 'Gansu'),
    ('Wuxi', 'Jiangsu'),
    ('Wuzhishan', 'Hainan'),
    ('Wuzhong', 'Ningxia'),
    ('Wuzhou', 'Guangxi'),
    ('Xi''an', 'Shaanxi'),
    ('Xiamen', 'Fujian'),
    ('Xiangtan', 'Hunan'),
    ('Xiangxi', 'Hunan'),
    ('Xiangyang', 'Hubei'),
    ('Xianning', 'Hubei'),
    ('Xiantao', 'Hubei'),
    ('Xianyang', 'Shaanxi'),
    ('Xiaogan', 'Hubei'),
    ('Xilingol', 'Inner Mongolia'),
    ('Xingtai', 'Hebei'),
    ('Xining', 'Qinghai'),
    ('Xinjiang', 'Xinjiang'),
    ('Xinxiang', 'Henan'),
    ('Xinyang', 'Henan'),
    ('Xinyu', 'Jiangxi'),
    ('Xinzhou', 'Shanxi'),
    ('Xishuangbanna', 'Yunnan'),
    ('Xuancheng', 'Anhui'),
    ('Xuchang', 'Henan'),
    ('Xuzhou', 'Jiangsu'),
    ('Ya''an', 'Sichuan'),
    ('Yan''an', 'Shaanxi'),
    ('Yanbian', 'Jilin'),
    ('Yancheng', 'Jiangsu'),
    ('Yangjiang', 'Guangdong'),
    ('Yangquan', 'Shanxi'),
    ('Yangzhou', 'Jiangsu'),
    ('Yantai', 'Shandong'),
    ('Yibin', 'Sichuan'),
    ('Yichang', 'Hubei'),
    ('Yichun', 'Jiangxi'),
    ('Yinchuan', 'Ningxia'),
    ('Yingkou', 'Liaoning'),
    ('Yingtan', 'Jiangxi'),
    ('Yiyang', 'Hunan'),
    ('Yongzhou', 'Hunan'),
    ('Yueyang', 'Hunan'),
    ('Yuncheng', 'Shanxi'),
    ('Yunfu', 'Guangdong'),
    ('Yunnan', 'Yunnan'),
    ('Yushu', 'Qinghai'),
    ('Yuxi', 'Yunnan'),
    ('Zaozhuang', 'Shandong'),
    ('Zhangjiajie', 'Hunan'),
    ('Zhangjiakou', 'Hebei'),
    ('Zhangye', 'Gansu'),
    ('Zhangzhou', 'Fujian'),
    ('Zhanjiang', 'Guangdong'),
    ('Zhaoqing', 'Guangdong'),
    ('Zhaotong', 'Yunnan'),
    ('Zhejiang', 'Zhejiang'),
    ('Zhengzhou', 'Henan'),
    ('Zhenjiang', 'Jiangsu'),
    ('Zhongshan', 'Guangdong'),
    ('Zhongwei', 'Ningxia'),
    ('Zhoukou', 'Henan'),
    ('Zhoushan', 'Zhejiang'),
    ('Zhuhai', 'Guangdong'),
    ('Zhumadian', 'Henan'),
    ('Zhuzhou', 'Hunan'),
    ('Zibo', 'Shandong'),
    ('Zigong', 'Sichuan'),
    ('Ziyang', 'Sichuan'),
    ('Zunyi', 'Guizhou')
) AS m(city, prov)
WHERE u.province IS NULL AND u.city = m.city;

UPDATE public.universities
SET city = NULL
WHERE city = ''
   OR city IN (
  'Anhui','Fujian','Gansu','Guangdong','Guangxi','Guizhou','Hainan','Hebei',
  'Heilongjiang','Henan','Hubei','Hunan','Inner Mongolia','Jiangsu','Jiangxi',
  'Jilin','Liaoning','Ningxia','Qinghai','Shaanxi','Shandong','Shanxi','Sichuan',
  'Tibet','Xinjiang','Yunnan','Zhejiang'
);
